"""Review UI: browse/compare scripts generated by scripts/eval_generation.py
(out/eval/*.json + out/generation_runs*.jsonl), and -- since the "生成" mode
below -- trigger a real generation run directly from the browser.

Every widget here reads/writes through src/bixiascribe/review.py and
src/bixiascribe/generation.py, neither of which import streamlit -- per the
武俠 RPG 劇本 RAG 架構方案 doc, Streamlit is a disposable "臨時駕駛艙" for this
stage, meant to be swappable for a Tauri desktop app later without touching
the data/generation layers. The 生成 mode runs a real crew (API key + Chroma
index required); the other three modes stay read-only, no tokens spent.

Run with:
    pip install -r requirements-ui.txt
    .venv/bin/streamlit run ui/app.py
"""
from __future__ import annotations

import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO_ROOT / "src"))

import streamlit as st  # noqa: E402

from bixiascribe import config, generation, length  # noqa: E402
from bixiascribe.review import (  # noqa: E402
    RunRecord,
    ScriptRecord,
    discover_scripts,
    event_titles,
    group_by_requirement,
    load_run_records,
    load_script,
    npc_names,
    overview_rows,
    requirement_slug,
    variant_names,
)
from bixiascribe.schema import Event, Script, validate_references  # noqa: E402

st.set_page_config(page_title="BiXiaScribe 劇本檢視", layout="wide")

# Catches the exact failure mode that motivated this check: `streamlit run
# ui/app.py` resolved via a system/anaconda `streamlit` on PATH instead of
# `.venv/bin/streamlit` -- the app still imports and runs fine (streamlit
# itself doesn't care), but the interpreter's torch is then too old for
# bge-m3 (see embedding.py::check_backend_env()), and every
# wuxia_corpus_search call during a real generation silently degrades to a
# "檢索失敗" text message for the whole run (crew/tools.py never raises on
# this). Read-only browsing still works under the wrong interpreter, so this
# warns rather than st.stop()s.
_venv_dir = _REPO_ROOT / ".venv"
if _venv_dir.is_dir() and Path(sys.prefix).resolve() != _venv_dir.resolve():
    st.error(
        f"⚠ 目前 Streamlit 跑在 `{sys.executable}`，不是專案的 `.venv`。"
        "語料檢索（wuxia_corpus_search）很可能會靜默失敗。請改用：\n\n"
        "```\n.venv/bin/streamlit run ui/app.py\n```"
    )


# ---- cached data access ----


@st.cache_data(show_spinner=False)
def _index() -> list[ScriptRecord]:
    return discover_scripts()


@st.cache_data(show_spinner=False)
def _overview() -> list[dict]:
    return overview_rows(_index())


@st.cache_data(show_spinner=False)
def _script(path_str: str, mtime: float) -> Script:
    # mtime is part of the cache key so an edited/regenerated file on disk
    # invalidates the cached parse automatically.
    return load_script(Path(path_str))


def _load(rec: ScriptRecord) -> Script | None:
    if rec.path is None:
        return None
    return _script(str(rec.path), rec.path.stat().st_mtime)


def _record_label(rec: ScriptRecord) -> str:
    rep_suffix = f" (rep{rec.rep})" if rec.rep else ""
    return f"{rec.variant}{rep_suffix}"


def _requirement_label(key: str, records: list[ScriptRecord]) -> str:
    slug = records[0].slug if records else ""
    short = key if len(key) <= 30 else key[:30] + "…"
    return f"{short}  ({slug})" if slug else short


# ---- shared render helpers ----


def _render_run_meta(run) -> None:
    if run is None:
        st.caption("沒有對應的執行紀錄（metadata 來源：檔名推斷）")
        return
    cols = st.columns(3)
    cols[0].write(f"**編劇模型**：{run.model_writer or '—'}")
    cols[1].write(f"**對話模型**：{run.model_dialogue or '—'}")
    cols[2].write(f"**校對模型**：{run.model_proof or '—'}")
    cols = st.columns(4)
    cols[0].metric("耗時 (s)", f"{run.elapsed_s:.1f}")
    cols[1].metric("retrieval_calls", run.retrieval_calls)
    cols[2].metric("repair_attempts", run.repair_attempts)
    cols[3].metric("total_tokens", run.token_usage.get("total_tokens", "—"))
    st.caption(f"coerced_from：{run.coerced_from or '—'} ｜ 來源紀錄：{run.source_log or '—'}")
    if not run.retrieval_enabled:
        st.info("本次刻意未使用語料檢索（不檢索語料庫）。")
    elif run.retrieval_calls == 0:
        st.warning("⚠ 對話 agent 從未呼叫 wuxia_corpus_search（retrieval_calls = 0）")
    if run.retrieval_failures > 0:
        st.error(
            f"⚠ 語料檢索失敗 {run.retrieval_failures} 次"
            "——請確認是用 `.venv/bin/streamlit` 執行、且索引已建立。"
        )
    if run.retrieval_queries:
        st.code("\n".join(run.retrieval_queries), language=None)
    if run.error:
        st.error(run.error)


def _render_event(event: Event, names: dict[str, str], titles: dict[str, str]) -> None:
    st.caption(event.summary)
    for trig in event.triggers:
        st.caption(f"觸發：{trig.type} — {trig.condition}")

    if not event.dialogue:
        st.caption("（無對話）")
    for line in event.dialogue:
        speaker = names.get(line.npc_id, f"⚠️ {line.npc_id}")
        emo = f"（{line.emotion}）" if line.emotion else ""
        st.markdown(f"**{speaker}**{emo}：{line.line}")

    for branch in event.branches:
        target = titles.get(branch.next_event_id, f"⚠️ {branch.next_event_id}")
        st.markdown(f"↳ **{branch.choice_text}** → {target}")
        extra = " ｜ ".join(
            f"{label}：{value}"
            for label, value in (("條件", branch.condition), ("效果", branch.effects))
            if value
        )
        if extra:
            st.caption(extra)


def _render_script(script: Script, rec: ScriptRecord) -> None:
    st.subheader(script.title)
    st.caption(script.premise)

    problems = validate_references(script)
    if problems:
        st.error("交叉參照有問題：\n" + "\n".join(f"- {p}" for p in problems))
    else:
        st.success("交叉參照無誤")

    metrics = overview_rows([rec])[0]
    cols = st.columns(5)
    cols[0].metric("事件", metrics["events"])
    cols[1].metric("NPC", metrics["npcs"])
    cols[2].metric("分支", metrics["branches"])
    cols[3].metric("對話句數", metrics["dialogue_lines"])
    cols[4].metric("平均句長", f"{metrics['avg_line_chars']:.1f}")

    names = npc_names(script)
    titles = event_titles(script)

    tab_events, tab_npc, tab_var, tab_run, tab_json = st.tabs(
        ["事件", "NPC", "變數", "執行紀錄", "原始 JSON"]
    )
    with tab_events:
        for i, event in enumerate(script.events):
            with st.expander(f"{i + 1}. {event.title} — {event.location}", expanded=(i == 0)):
                _render_event(event, names, titles)
    with tab_npc:
        st.dataframe([n.model_dump() for n in script.npcs], width="stretch")
    with tab_var:
        st.dataframe([v.model_dump() for v in script.variables], width="stretch")
    with tab_run:
        _render_run_meta(rec.run)
        if rec.source != "jsonl":
            st.info(f"metadata 來源：{rec.source}（找不到對應的 JSONL 執行紀錄）")
    with tab_json:
        st.json(script.model_dump())


# ---- generation mode helpers ----


def _record_for_result(res: generation.GenerationResult) -> ScriptRecord:
    """Wrap a fresh GenerationResult in the same ScriptRecord shape
    discover_scripts() produces from disk, so _render_script/_render_run_meta
    render a just-generated script with zero new render code."""
    return ScriptRecord(
        key=res.script_path.stem if res.script_path else f"{res.variant}@pending",
        path=res.script_path,
        variant=res.variant,
        slug=requirement_slug(res.requirement),
        rep=res.rep,
        requirement=res.requirement,
        run=RunRecord.from_row(res.row, source_log=generation.UI_RUN_LOG.name),
        source="jsonl" if res.script_path else "run-only",
    )


@st.fragment(run_every=1.0)
def _render_generation_progress(job: generation.GenerationJob) -> None:
    snap = job.snapshot()

    if snap.status == "running":
        # A batch awaiting confirmation is rendered by the static
        # _render_batch_confirmation() below instead, outside this
        # every-1s-repainting fragment -- inside the fragment, a button
        # click could get wiped out by the next repaint landing mid-click.
        # Leaving this fragment via st.rerun() hands control to the page's
        # non-fragment branch (see the "生成" mode body), which re-checks
        # snap.awaiting_confirmation on every full rerun.
        if snap.awaiting_confirmation:
            st.rerun()

        # phase_total == 0 means "layered" mode's unknown-ahead-of-time
        # batch count (see JobSnapshot's docstring) -- show a step counter
        # instead of a fraction bar in that case.
        if snap.phase_total > 0:
            st.progress(snap.phase_index / snap.phase_total)
        else:
            st.caption(f"第 {snap.phase_index} 步")
        phase_label = snap.phase or "準備中"
        st.caption(f"{phase_label} · {snap.elapsed_s:.0f}s / 預估 130–240s")
        if snap.log:
            st.code("\n".join(snap.log[-12:]), language=None)

        if st.button("取消", key="cancel_gen"):
            job.cancel()
        return

    # Terminal state: clear cached discovery so the new script/row shows up
    # elsewhere, then leave the fragment for a full-app rerun.
    st.cache_data.clear()
    if snap.status == "done" and snap.result is not None and snap.result.ok:
        st.session_state["gen_last_result"] = snap.result
    elif snap.status == "cancelled":
        st.warning("已取消本次生成。")
    else:
        st.session_state["gen_last_result"] = snap.result  # may be None
        st.session_state["gen_last_error"] = snap.error or (
            snap.result.error if snap.result else "生成失敗（原因不明）。"
        )
    del st.session_state["gen_job"]
    st.rerun()


def _render_batch_confirmation(job: generation.GenerationJob, snap: generation.JobSnapshot) -> None:
    """Static (non-fragment) panel shown while a layered run's scenes batch
    is staged awaiting confirm_batch()/reject_batch() -- rendered outside
    _render_generation_progress()'s @st.fragment(run_every=1.0) so a button
    click can't be wiped out by the next automatic repaint landing mid-click
    (see that function's docstring). Renders the staged scenes' actual
    content (via the existing _render_event, zero new render code) instead
    of just their beat ids, so confirming isn't a blind decision."""
    st.subheader("本批場次待確認")
    st.caption(f"run_id：{snap.run_id} ｜ 已耗時 {snap.elapsed_s:.0f}s")

    scenes = job.pending_scenes()
    names, titles = job.scene_context()
    if not scenes:
        st.info(f"本批已生成 {len(snap.pending_scene_ids)} 場：{'、'.join(snap.pending_scene_ids)}")
    for i, event in enumerate(scenes):
        with st.expander(f"{i + 1}. {event.title} — {event.location}", expanded=(i == 0)):
            _render_event(event, names, titles)

    col1, col2, col3 = st.columns(3)
    if col1.button("確認繼續", key="confirm_batch"):
        job.confirm_batch()
        st.rerun()
    if col2.button("重新生成本批", key="reject_batch"):
        job.reject_batch()
        st.rerun()
    if col3.button("取消", key="cancel_gen_confirm"):
        job.cancel()
        st.rerun()


# ---- page ----

records = _index()
run_count = len(load_run_records())

st.sidebar.caption(
    f"資料來源：`{config.EVAL_SCRIPTS_DIR}`\n\n"
    f"{sum(1 for r in records if r.path)} 份劇本 ｜ {run_count} 筆執行紀錄"
)
if st.sidebar.button("重新載入"):
    st.cache_data.clear()
    st.rerun()

mode_options = ["單篇閱讀", "並排比較", "總覽表", "生成"]
default_mode = "生成" if not records else "單篇閱讀"
mode = st.sidebar.radio("模式", mode_options, index=mode_options.index(default_mode))

groups = group_by_requirement(records)
requirement_keys = list(groups.keys())

if mode != "生成" and not records:
    st.warning(
        "找不到任何已生成的劇本。用左側的「生成」模式產生一份，或先跑：\n\n"
        "```\npython scripts/eval_generation.py --dry-run   # 先零成本檢查\n"
        "python scripts/eval_generation.py                # 實際生成\n```"
    )
    st.stop()

if mode == "生成":
    st.title("生成新劇本")

    job: generation.GenerationJob | None = st.session_state.get("gen_job")
    if job is not None:
        job_snap = job.snapshot()
        if job_snap.status == "running" and job_snap.awaiting_confirmation:
            # Rendered outside the every-1s @st.fragment so a button click
            # can't be wiped out by an automatic repaint mid-click -- see
            # _render_batch_confirmation()'s docstring.
            _render_batch_confirmation(job, job_snap)
        else:
            _render_generation_progress(job)
        st.stop()

    requirement = st.text_area("劇情需求", height=140, key="gen_requirement")

    all_variants = [v for v in generation.load_variants() if v.ui_visible]
    variant_choice = st.selectbox(
        "模型變體",
        [*all_variants, "自訂"],
        format_func=lambda v: v if isinstance(v, str) else v.name,
    )
    if variant_choice == "自訂":
        with st.expander("自訂模型", expanded=True):
            writer = st.text_input("編劇模型", value=config.LLM_MODEL_WRITER)
            dialogue = st.text_input("對話模型", value=config.LLM_MODEL_DIALOGUE)
            proof = st.text_input("校對模型", value=config.LLM_MODEL_PROOF)
        variant = generation.Variant(
            name="custom", writer=writer, dialogue=dialogue, proof=proof
        )
    else:
        variant = variant_choice
        if variant.note:
            st.caption(variant.note)

    use_layered = st.checkbox(
        "使用分層生成管線（layered，可逐批確認場次）",
        value=config.PIPELINE_MODE == "layered",
        help="拆書 → 排場 → 逐場戲並行生成，每批可先看過再決定是否繼續；"
        "未勾選則沿用原本一次性生成的管線。",
    )

    no_retrieval = st.checkbox(
        "不檢索語料庫（省 token，改用模型自身武俠語感）",
        value=not (
            variant.use_retrieval if variant.use_retrieval is not None else config.RETRIEVAL_ENABLED
        ),
        help="關閉後，對話/scene_writer agent 不會呼叫 wuxia_corpus_search——"
        "不需要 Chroma 索引或本機 embedding 模型，也能省下最大宗的 token 花費"
        "（見 CLAUDE.md 的模型組合 A/B 數據：retrieval 呼叫次數與 token 用量高度相關）。"
        "適合測試 glm-5.2 等武俠語感本身較好的模型是否真的需要語料檢索。",
    )

    # Default to the selected variant's own script_length so picking a
    # predefined variant (not 自訂) preserves its declared length unless the
    # user actively changes the selector -- see design.md's "UI length
    # selector UX".
    variant_script_length = variant.script_length or "short"
    length_presets = ("short", "medium", "long")
    if variant_script_length in length_presets:
        default_length_option = variant_script_length
        default_custom_targets = length.parse_length_spec("short").targets
    else:
        default_length_option = "自訂"
        default_custom_targets = length.parse_length_spec(variant_script_length).targets

    length_option = st.selectbox(
        "劇本篇幅",
        [*length_presets, "自訂"],
        index=[*length_presets, "自訂"].index(default_length_option),
    )
    if length_option == "自訂":
        with st.expander("自訂篇幅", expanded=True):
            length_events = st.text_input(
                "events（事件數）", value=default_custom_targets["events"]
            )
            length_chapters = st.text_input(
                "chapters（章數）", value=default_custom_targets["chapters"]
            )
            length_beats = st.text_input(
                "beats_per_chapter（每章場次數）", value=default_custom_targets["beats_per_chapter"]
            )
            length_dialogue = st.text_input(
                "min_dialogue（最少台詞段落）", value=default_custom_targets["min_dialogue"]
            )
        script_length = (
            f"custom:events={length_events},chapters={length_chapters},"
            f"beats_per_chapter={length_beats},min_dialogue={length_dialogue}"
        )
    else:
        script_length = length_option

    problems = generation.preflight(check_index=not no_retrieval, check_embedding=not no_retrieval)
    ignore_checks = False
    if problems:
        for p in problems:
            st.error(p)
        ignore_checks = st.checkbox("忽略檢查，仍要執行（例如 LLM_BACKEND=fake 的離線測試）")

    disabled = bool(requirement.strip()) is False or (bool(problems) and not ignore_checks)
    if st.button("開始生成", disabled=disabled):
        ui_variant = generation.Variant(
            name=generation.ui_variant_name(variant.name),
            note=variant.note,
            writer=variant.writer,
            dialogue=variant.dialogue,
            proof=variant.proof,
            extractor=variant.extractor,
            beat_expander=variant.beat_expander,
            scene_writer=variant.scene_writer,
            session_doc_max_tokens=variant.session_doc_max_tokens,
            script_length=variant.script_length,
            use_retrieval=not no_retrieval,
        )
        new_job = generation.GenerationJob(
            requirement,
            ui_variant,
            pipeline_mode="layered" if use_layered else "legacy",
            script_length=script_length,
            use_retrieval=not no_retrieval,
        )
        try:
            new_job.start()
        except generation.GenerationBusyError as exc:
            st.error(str(exc))
        else:
            st.session_state["gen_job"] = new_job
            st.session_state.pop("gen_last_result", None)
            st.session_state.pop("gen_last_error", None)
            st.rerun()

    if "gen_last_error" in st.session_state:
        st.error(st.session_state["gen_last_error"])
        failed_result = st.session_state.get("gen_last_result")
        if failed_result is not None and failed_result.row:
            failed_run = RunRecord.from_row(
                failed_result.row, source_log=generation.UI_RUN_LOG.name
            )
            _render_run_meta(failed_run)
        if st.button("清除本次結果"):
            del st.session_state["gen_last_error"]
            st.session_state.pop("gen_last_result", None)
            st.rerun()

    if "gen_last_result" in st.session_state and "gen_last_error" not in st.session_state:
        result: generation.GenerationResult = st.session_state["gen_last_result"]
        rec = _record_for_result(result)
        _render_script(_load(rec), rec)
        if st.button("清除本次結果"):
            del st.session_state["gen_last_result"]
            st.rerun()

elif mode == "總覽表":
    st.title("總覽表")
    st.dataframe(_overview(), width="stretch")

elif mode == "單篇閱讀":
    st.title("單篇閱讀")
    req_key = st.sidebar.selectbox(
        "劇情需求", requirement_keys, format_func=lambda k: _requirement_label(k, groups[k])
    )
    group = groups[req_key]
    variants = sorted({r.variant for r in group})
    variant = st.sidebar.selectbox("變體", variants)
    reps = sorted({r.rep for r in group if r.variant == variant})
    rep = st.sidebar.selectbox("Rep", reps) if len(reps) > 1 else reps[0]

    rec = next((r for r in group if r.variant == variant and r.rep == rep), None)
    if rec is None:
        st.info("找不到此組合的劇本。")
    elif rec.path is None:
        st.error("此次執行沒有產生劇本檔案（生成失敗）。")
        _render_run_meta(rec.run)
    else:
        _render_script(_load(rec), rec)

else:  # 並排比較
    st.title("並排比較")
    req_key = st.sidebar.selectbox(
        "劇情需求", requirement_keys, format_func=lambda k: _requirement_label(k, groups[k])
    )
    group = groups[req_key]
    all_variants = variant_names(group)
    selected = st.sidebar.multiselect("變體", all_variants, default=all_variants[:2])
    reps = sorted({r.rep for r in group})
    rep = st.sidebar.selectbox("Rep", reps) if len(reps) > 1 else (reps[0] if reps else 0)

    if not selected:
        st.info("請至少選擇一個變體。")
        st.stop()

    selected_records = []
    for variant in selected:
        rec = next((r for r in group if r.variant == variant and r.rep == rep), None)
        selected_records.append(rec)

    present = [r for r in selected_records if r is not None]
    if present:
        st.dataframe(overview_rows(present), width="stretch")

    show_all = st.checkbox("顯示全部事件（否則用序號滑桿逐一比對）", value=False)
    max_events = max((len(_load(r).events) for r in present if r.path), default=0)
    event_idx = None
    if not show_all and max_events > 0:
        event_idx = st.slider("事件序號", 1, max_events, 1) - 1

    cols = st.columns(len(selected))
    for col, variant, rec in zip(cols, selected, selected_records):
        with col:
            st.markdown(f"### {variant}")
            if rec is None:
                st.info("此變體無此需求的劇本")
                continue
            if rec.path is None:
                st.error("此次執行沒有產生劇本檔案（生成失敗）。")
                if rec.run is not None:
                    st.caption(rec.run.error)
                continue

            script = _load(rec)
            names = npc_names(script)
            titles = event_titles(script)
            st.caption(script.title)
            problems = validate_references(script)
            st.caption("✅ 交叉參照無誤" if not problems else f"⚠️ {len(problems)} 個交叉參照問題")

            if show_all or event_idx is None:
                events_to_show = script.events
            elif event_idx < len(script.events):
                events_to_show = script.events[event_idx : event_idx + 1]
            else:
                events_to_show = []
            container = st.container(height=600) if show_all else st.container()
            with container:
                if not events_to_show:
                    st.caption("（此變體沒有這一個序號的事件）")
                for event in events_to_show:
                    st.markdown(f"**{event.title}** — {event.location}")
                    _render_event(event, names, titles)
                    st.divider()
