"""Stage 3 read-only review UI: browse and compare scripts generated by
scripts/eval_generation.py (out/eval/*.json + out/generation_runs*.jsonl).

Read-only by design: no pipeline call, no API key, no Chroma index, no
tokens spent. Every widget here reads from src/bixiascribe/review.py, which
has no streamlit import of its own -- per the 武俠 RPG 劇本 RAG 架構方案 doc,
Streamlit is a disposable "臨時駕駛艙" for this stage, meant to be swappable
for a Tauri desktop app later without touching the data layer.

Run with:
    pip install -r requirements-ui.txt
    streamlit run ui/app.py
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import streamlit as st  # noqa: E402

from bixiascribe import config  # noqa: E402
from bixiascribe.review import (  # noqa: E402
    ScriptRecord,
    discover_scripts,
    event_titles,
    group_by_requirement,
    load_run_records,
    load_script,
    npc_names,
    overview_rows,
    variant_names,
)
from bixiascribe.schema import Event, Script, validate_references  # noqa: E402

st.set_page_config(page_title="BiXiaScribe 劇本檢視", layout="wide")


# ---- cached data access ----


@st.cache_data(show_spinner=False)
def _index() -> list[ScriptRecord]:
    return discover_scripts()


@st.cache_data(show_spinner=False)
def _overview() -> list[dict]:
    return overview_rows(_index())


@st.cache_data(show_spinner=False)
def _script(path_str: str, mtime: float) -> Script:
    # mtime is part of the cache key so an edited/regenerated file on disk
    # invalidates the cached parse automatically.
    return load_script(Path(path_str))


def _load(rec: ScriptRecord) -> Script | None:
    if rec.path is None:
        return None
    return _script(str(rec.path), rec.path.stat().st_mtime)


def _record_label(rec: ScriptRecord) -> str:
    rep_suffix = f" (rep{rec.rep})" if rec.rep else ""
    return f"{rec.variant}{rep_suffix}"


def _requirement_label(key: str, records: list[ScriptRecord]) -> str:
    slug = records[0].slug if records else ""
    short = key if len(key) <= 30 else key[:30] + "…"
    return f"{short}  ({slug})" if slug else short


# ---- shared render helpers ----


def _render_run_meta(run) -> None:
    if run is None:
        st.caption("沒有對應的執行紀錄（metadata 來源：檔名推斷）")
        return
    cols = st.columns(3)
    cols[0].write(f"**編劇模型**：{run.model_writer or '—'}")
    cols[1].write(f"**對話模型**：{run.model_dialogue or '—'}")
    cols[2].write(f"**校對模型**：{run.model_proof or '—'}")
    cols = st.columns(4)
    cols[0].metric("耗時 (s)", f"{run.elapsed_s:.1f}")
    cols[1].metric("retrieval_calls", run.retrieval_calls)
    cols[2].metric("repair_attempts", run.repair_attempts)
    cols[3].metric("total_tokens", run.token_usage.get("total_tokens", "—"))
    st.caption(f"coerced_from：{run.coerced_from or '—'} ｜ 來源紀錄：{run.source_log or '—'}")
    if run.retrieval_calls == 0:
        st.warning("⚠ 對話 agent 從未呼叫 wuxia_corpus_search（retrieval_calls = 0）")
    if run.retrieval_queries:
        st.code("\n".join(run.retrieval_queries), language=None)
    if run.error:
        st.error(run.error)


def _render_event(event: Event, names: dict[str, str], titles: dict[str, str]) -> None:
    st.caption(event.summary)
    for trig in event.triggers:
        st.caption(f"觸發：{trig.type} — {trig.condition}")

    if not event.dialogue:
        st.caption("（無對話）")
    for line in event.dialogue:
        speaker = names.get(line.npc_id, f"⚠️ {line.npc_id}")
        emo = f"（{line.emotion}）" if line.emotion else ""
        st.markdown(f"**{speaker}**{emo}：{line.line}")

    for branch in event.branches:
        target = titles.get(branch.next_event_id, f"⚠️ {branch.next_event_id}")
        st.markdown(f"↳ **{branch.choice_text}** → {target}")
        extra = " ｜ ".join(
            f"{label}：{value}"
            for label, value in (("條件", branch.condition), ("效果", branch.effects))
            if value
        )
        if extra:
            st.caption(extra)


def _render_script(script: Script, rec: ScriptRecord) -> None:
    st.subheader(script.title)
    st.caption(script.premise)

    problems = validate_references(script)
    if problems:
        st.error("交叉參照有問題：\n" + "\n".join(f"- {p}" for p in problems))
    else:
        st.success("交叉參照無誤")

    metrics = overview_rows([rec])[0]
    cols = st.columns(5)
    cols[0].metric("事件", metrics["events"])
    cols[1].metric("NPC", metrics["npcs"])
    cols[2].metric("分支", metrics["branches"])
    cols[3].metric("對話句數", metrics["dialogue_lines"])
    cols[4].metric("平均句長", f"{metrics['avg_line_chars']:.1f}")

    names = npc_names(script)
    titles = event_titles(script)

    tab_events, tab_npc, tab_var, tab_run, tab_json = st.tabs(
        ["事件", "NPC", "變數", "執行紀錄", "原始 JSON"]
    )
    with tab_events:
        for i, event in enumerate(script.events):
            with st.expander(f"{i + 1}. {event.title} — {event.location}", expanded=(i == 0)):
                _render_event(event, names, titles)
    with tab_npc:
        st.dataframe([n.model_dump() for n in script.npcs], width="stretch")
    with tab_var:
        st.dataframe([v.model_dump() for v in script.variables], width="stretch")
    with tab_run:
        _render_run_meta(rec.run)
        if rec.source != "jsonl":
            st.info(f"metadata 來源：{rec.source}（找不到對應的 JSONL 執行紀錄）")
    with tab_json:
        st.json(script.model_dump())


# ---- page ----

records = _index()
run_count = len(load_run_records())

st.sidebar.caption(
    f"資料來源：`{config.EVAL_SCRIPTS_DIR}`\n\n"
    f"{sum(1 for r in records if r.path)} 份劇本 ｜ {run_count} 筆執行紀錄"
)
if st.sidebar.button("重新載入"):
    st.cache_data.clear()
    st.rerun()

if not records:
    st.warning(
        "找不到任何已生成的劇本。`out/` 是 gitignored，需要先跑：\n\n"
        "```\npython scripts/eval_generation.py --dry-run   # 先零成本檢查\n"
        "python scripts/eval_generation.py                # 實際生成\n```"
    )
    st.stop()

mode = st.sidebar.radio("模式", ["單篇閱讀", "並排比較", "總覽表"])

groups = group_by_requirement(records)
requirement_keys = list(groups.keys())

if mode == "總覽表":
    st.title("總覽表")
    st.dataframe(_overview(), width="stretch")

elif mode == "單篇閱讀":
    st.title("單篇閱讀")
    req_key = st.sidebar.selectbox(
        "劇情需求", requirement_keys, format_func=lambda k: _requirement_label(k, groups[k])
    )
    group = groups[req_key]
    variants = sorted({r.variant for r in group})
    variant = st.sidebar.selectbox("變體", variants)
    reps = sorted({r.rep for r in group if r.variant == variant})
    rep = st.sidebar.selectbox("Rep", reps) if len(reps) > 1 else reps[0]

    rec = next((r for r in group if r.variant == variant and r.rep == rep), None)
    if rec is None:
        st.info("找不到此組合的劇本。")
    elif rec.path is None:
        st.error("此次執行沒有產生劇本檔案（生成失敗）。")
        _render_run_meta(rec.run)
    else:
        _render_script(_load(rec), rec)

else:  # 並排比較
    st.title("並排比較")
    req_key = st.sidebar.selectbox(
        "劇情需求", requirement_keys, format_func=lambda k: _requirement_label(k, groups[k])
    )
    group = groups[req_key]
    all_variants = variant_names(group)
    selected = st.sidebar.multiselect("變體", all_variants, default=all_variants[:2])
    reps = sorted({r.rep for r in group})
    rep = st.sidebar.selectbox("Rep", reps) if len(reps) > 1 else (reps[0] if reps else 0)

    if not selected:
        st.info("請至少選擇一個變體。")
        st.stop()

    selected_records = []
    for variant in selected:
        rec = next((r for r in group if r.variant == variant and r.rep == rep), None)
        selected_records.append(rec)

    present = [r for r in selected_records if r is not None]
    if present:
        st.dataframe(overview_rows(present), width="stretch")

    show_all = st.checkbox("顯示全部事件（否則用序號滑桿逐一比對）", value=False)
    max_events = max((len(_load(r).events) for r in present if r.path), default=0)
    event_idx = None
    if not show_all and max_events > 0:
        event_idx = st.slider("事件序號", 1, max_events, 1) - 1

    cols = st.columns(len(selected))
    for col, variant, rec in zip(cols, selected, selected_records):
        with col:
            st.markdown(f"### {variant}")
            if rec is None:
                st.info("此變體無此需求的劇本")
                continue
            if rec.path is None:
                st.error("此次執行沒有產生劇本檔案（生成失敗）。")
                if rec.run is not None:
                    st.caption(rec.run.error)
                continue

            script = _load(rec)
            names = npc_names(script)
            titles = event_titles(script)
            st.caption(script.title)
            problems = validate_references(script)
            st.caption("✅ 交叉參照無誤" if not problems else f"⚠️ {len(problems)} 個交叉參照問題")

            if show_all or event_idx is None:
                events_to_show = script.events
            elif event_idx < len(script.events):
                events_to_show = script.events[event_idx : event_idx + 1]
            else:
                events_to_show = []
            container = st.container(height=600) if show_all else st.container()
            with container:
                if not events_to_show:
                    st.caption("（此變體沒有這一個序號的事件）")
                for event in events_to_show:
                    st.markdown(f"**{event.title}** — {event.location}")
                    _render_event(event, names, titles)
                    st.divider()
